[package]
name = "widget_gallery"
version = "0.1.0"
edition = "2021"

[workspace]

[lib]
name = "widget_gallery"
crate-type = ["cdylib", "staticlib", "rlib"]
path = "src/lib.rs"

[[bin]]
name = "widget_gallery"
path = "src/main.rs"

[dependencies]
rosace = { path = "/Users/godwinjoseph/Development/Tezzera/rosace" }
rosace-ffi = { path = "/Users/godwinjoseph/Development/Tezzera/rosace-ffi" }

[build-dependencies]
rosace-asset-codegen = { path = "/Users/godwinjoseph/Development/Tezzera/rosace-asset-codegen" }
